const mapDBToModelForm = ({
    id,
    nama_kursus,
    jumlah_pertemuan,
    harga,
    nama,
    alamat,
    phone,
    ttl,
    pendidikan,
    agama,
    orangtua,
    pekerjaan,
    create_at,
    update_at,
    user_id,
}) => ({
    id,
    namaKursus: nama_kursus,
    jumlahPertemuan: jumlah_pertemuan,
    harga,
    nama,
    alamat,
    phone,
    ttl,
    pendidikan,
    agama,
    orangtua,
    pekerjaan,
    createdAt: create_at,
    updatedAt: update_at,
    userId: user_id,
});

module.exports = { mapDBToModelForm };